- name: Tell sidekiq to not accept new work
  shell: "{{ profile }}'reload {{sidekiq_job_name}}'"
  ignore_errors: true

- command: '/bin/true'
  name: 'Make sure sidekiq is started at the end'
  notify: restart sidekiq
